import './globals.css'
import { Montserrat,Inter } from 'next/font/google'

const inter = Inter({ weight:["100",'200','300','400','500'],subsets:["latin"] })

const monsterrat=Montserrat({weight:["100","200","300","400","500"],subsets:['latin']})

export const metadata = {
  title: 'Prithvi',
  description: 'Generated by create next app',
  
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={monsterrat.className}>{children}</body>
    </html>
  )
}
